#!/bin/sh

PANICA_SESSION=panica
PANICA_DIR="$HOME/.panica"
IRC_DIR="$PANICA_DIR/irc"

if [ -f "$PANICA_DIR/config" ]; then
    . "$PANICA_DIR/config"
fi


if [ -f "$IRC_HOST_CONF" ]; then
    . "$IRC_HOST_CONF"
fi

logfile="$IRC_DIR/$IRC_HOST/channels/$IRC_WHERE.log"

# nickserv login
if [ ! -z "$IRC_NICKSERV_PASS" ] && \
	[ "$IRC_WHERE" = "nickserv" ]; then
    tail -fn 0 "$IRC_DIR/$IRC_HOST/channels/nickserv.log" | \
	    grep -m 1 -E "^[0-9]+ <NickServ>n You are now identified for " &&
	    echo "join $(echo -n "$IRC_ROOMS_AUTOJOIN" | tr "$IFS" ",")" > "$IRC_DIR/$IRC_HOST/in" &
    echo "raw PRIVMSG NickServ :IDENTIFY $IRC_NICK $IRC_NICKSERV_PASS" > "$IRC_DIR/$IRC_HOST/in"
fi

# on ignore list
for channel in $IRC_ROOMS_IGNORE; do
    test "$channel" = "$IRC_WHERE" && exit
done

# alread open
if tmux list-windows -F '#{window_name}' | grep "$IRC_WHERE@$IRC_HOST"; then
    exit
fi

tmux new-window \
	-e "IRC_LOGFILE=$logfile" \
	-t "$PANICA_SESSION:" \
	-n "$IRC_WHERE@$IRC_HOST" \
	-- sh -c 'tail -fn 1000 "$IRC_LOGFILE" | jjp'


tmux list-windows -F '#{window_name} #{window_index}' | \
	grep "^$IRC_WHERE@$IRC_HOST" | \
	while read m i; do
    tmux split-window \
	-e "IRC_WHERE=$IRC_WHERE" \
	-e "IRC_HOST=$IRC_HOST" \
	-e "IRC_DIR=$IRC_DIR" \
	-t "$PANICA_SESSION:$i" \
	-l 1 \
	-- sh -c "${IRC_INPUT:-panica-input}"
    break
done

