#!/bin/sh

if [ -f "$IRC_HOST_CONF" ]; then
    . "$IRC_HOST_CONF"
fi

if [ -z "$IRC_NICKSERV_PASS" ]; then
    echo "join $(echo -n "$IRC_ROOMS_AUTOJOIN" | tr "$IFS" ",")" > "$IRC_DIR/$IRC_HOST/in"
fi
