#!/bin/sh

PANICA_SESSION=panica
PANICA_DIR="$HOME/.panica"
IRC_DIR="$PANICA_DIR/irc"

if [ -f "$PANICA_DIR/config" ]; then
    . "$PANICA_DIR/config"
fi

tmux list-windows -F '#{window_name} #{window_index}' | \
	grep "^$IRC_WHERE@$IRC_HOST" | \
	while read m i; do
    tmux kill-window -t "$PANICA_SESSION:$i"
    break
done
