#!/bin/sh -e
#
# Send stdin to a channel.
#
# Usage: panica-input <channel>
#
# Commands can be executed by prefixing them with a '/'.  Typing two
# slashes allows sending of messages with a slash in the beginning.
#
# Ripped off jj/extra/jji

channel="${IRC_WHERE:?Missing IRC_WHERE variable}"

fifo="$IRC_DIR/$IRC_HOST/in"
[ -p "$fifo" ] && [ -w "$fifo" ] ||
	exit 1

prompt() { [ -t 0 ] && printf '\033[0m%s\033[0m> ' "$channel" >&2 || :; }

while prompt "$channel" && IFS= read -r line || [ -n "$line" ]; do
	case $line in
		/part) line="${line#?} $channel" ;;
		/[!/]*) line=${line#?} ;;
		*) line="msg $channel $line" ;;
	esac
	printf %s\\n "$line"
done >"$fifo"
